spring:
  application:
    name: notification-service

  server:
    port: 0

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

# To enable all actuator endpoints
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

  management:
    tracing:
      sampling:
        probability: 1.0

