spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: xuv500
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# To enable circuit breaker
management:
  health:
    circuitbreakers:
      enabled: true
  # To enable all actuator endpoints
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4J properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

# Resilience4J timeout properties
  timelimiter:
    instances:
      inventory:
        timeout-duration:
          seconds: 3
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration:
          seconds: 5

# Resilience4J retry properties










