spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: xuv500

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/






