spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false

eur:
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

server:
  port: 8761
