spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: xuv500

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/






