spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: xuv500

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop

server:
  port: 8082





